### ISSUE TITLE
ZeroDivisionError in FirstByDowning

### ISSUE THREAD

**Issue by marcharper** [Axelrod-Python/Axelrod#1285]
There's an implicit assumption that `self.defections != 0` when `turn > 3` in the calculation of `beta` but if the `Match` is noisy this can be violated:

```
>>> import axelrod as axl
>>> player1 = axl.FirstByDowning()
>>> player2 = axl.Defector()
>>> match = axl.Match((player1, player2), turns=3, noise=0.99)
>>> match.play()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/repos/axelrod/Axelrod/axelrod/match.py", line 189, in play
    self.players[0], self.players[1], self.noise)
  File "/home/user/repos/axelrod/Axelrod/axelrod/match.py", line 141, in simultaneous_play
    s1, s2 = player.strategy(coplayer), coplayer.strategy(player)
  File "/home/user/repos/axelrod/Axelrod/axelrod/strategies/axelrod_first.py", line 268, in strategy
    beta = (self.number_opponent_cooperations_in_response_to_D /
ZeroDivisionError: division by zero
```

**Comment by marcharper** [comment]
This was found by hypothesis.

**Comment by marcharper** [comment]
In #1288 I replaced the denominator with `max(self.defections, 1)`. That removes the error but I'm not sure if it's precisely the right patch.

**Comment by drvinceknight** [comment]
Yeah I think it should be:

```
max(self.defections, 2)
```

There's obviously a lot of ambiguity here but to keep things consistent with the interpretation currently on offer in the docstring I think that's the correct way to go.
