### ISSUE TITLE
Testing issue with cache [Python 2/3 compatibility]

### ISSUE THREAD

**Issue by marcharper** [Axelrod-Python/Axelrod#385]
If you run the test suite in python 3 and then in python 2, this error occurs:

```
> python3 -m unittest discover
< All tests pass >
> python -m unittest discover
..................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................EEEE...............................................................................EE....................................EE
======================================================================
ERROR: test_add_tournament (axelrod.tests.unit.test_tournament_manager.TestTournamentManager)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/repos/axelrod/Axelrod/axelrod/tests/unit/test_tournament_manager.py", line 47, in test_add_tournament
    self.test_with_ecological)
  File "/home/user/repos/axelrod/Axelrod/axelrod/tournament_manager.py", line 30, in __init__
    self.load_cache = self._load_cache_from_file(cache_file)
  File "/home/user/repos/axelrod/Axelrod/axelrod/tournament_manager.py", line 163, in _load_cache_from_file
    deterministic_cache = pickle.load(io)
  File "/usr/lib/python2.7/pickle.py", line 1378, in load
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 886, in load_proto
    raise ValueError, "unsupported pickle protocol: %d" % proto
ValueError: unsupported pickle protocol: 3

<Same error 7 more times>
----------------------------------------------------------------------
Ran 1037 tests in 5.946s

FAILED (errors=8)
```

The reason is that python3 uses a different [pickle protocol](https://docs.python.org/3/library/pickle.html) (3 or 4) version than [python 2](https://docs.python.org/2/library/pickle.html) (protocol version 2). To resolve the issue we just need to delete the cache at appropriate times or change the protocol version to always use 2.

**Comment by marcharper** [comment]
To resolve this issue, we just need to have the tests use a different cache filename and delete it afterwards.

**Comment by marcharper** [comment]
Switching to cloudpickle seems to have resolved this.
