### ISSUE TITLE
Tests currently fail on py2

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/Axelrod#465]
#464 has introduced a bug, tests fail on py2:

```
........................................Falsifying example: test_property_serial_play(self=<axelrod.tests.unit.test_tournament.TestTournament testMethod=test_property_serial_play>, s=[<class 'axelrod.strategies.memoryone.ALLCorALLD'>, <class 'axelrod.strategies.grudger.Aggravater'>, <class 'axelrod.strategy_transformers.BackStabber'>, <class 'axelrod.strategies.alternator.Alternator'>, <class 'axelrod.strategies.mindreader.MindReader'>], turns=2, repetitions=2, rm=random.seed(0))
E..............
======================================================================
ERROR: test_property_serial_play (axelrod.tests.unit.test_tournament.TestTournament)
Test serial play using hypothesis
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/Axelrod-Python/Axelrod/axelrod/tests/unit/test_tournament.py", line 110, in test_property_serial_play
    min_size=2,  # Errors are returned if less than 2 strategies
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/hypothesis/core.py", line 502, in wrapped_test
    print_example=True, is_final=True
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/hypothesis/executors.py", line 57, in default_new_style_executor
    return function(data)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/hypothesis/core.py", line 103, in run
    return test(*args, **kwargs)
  File "/home/travis/build/Axelrod-Python/Axelrod/axelrod/tests/unit/test_tournament.py", line 129, in test_property_serial_play
    results = tournament.play()
  File "/home/travis/build/Axelrod-Python/Axelrod/axelrod/tournament.py", line 49, in play
    self._run_serial_repetitions(self._outcome)
  File "/home/travis/build/Axelrod-Python/Axelrod/axelrod/tournament.py", line 82, in _run_serial_repetitions
    self._run_single_repetition(outcome)
  File "/home/travis/build/Axelrod-Python/Axelrod/axelrod/tournament.py", line 75, in _run_single_repetition
    output = self._play_round_robin()
  File "/home/travis/build/Axelrod-Python/Axelrod/axelrod/tournament.py", line 146, in _play_round_robin
    return round_robin.play()
  File "/home/travis/build/Axelrod-Python/Axelrod/axelrod/round_robin.py", line 39, in play
    player1_index, player2_index)
  File "/home/travis/build/Axelrod-Python/Axelrod/axelrod/round_robin.py", line 57, in _score_single_interaction
    player1, player2, classes)
  File "/home/travis/build/Axelrod-Python/Axelrod/axelrod/round_robin.py", line 100, in _play_single_interaction
    player1.play(player2, self._noise)
  File "/home/travis/build/Axelrod-Python/Axelrod/axelrod/player.py", line 127, in play
    s1, s2 = self.strategy(opponent), opponent.strategy(self)
  File "/home/travis/build/Axelrod-Python/Axelrod/axelrod/strategies/mindreader.py", line 76, in strategy
    best_strategy = look_ahead(self, opponent, game)
  File "/home/travis/build/Axelrod-Python/Axelrod/axelrod/strategies/mindreader.py", line 35, in look_ahead
    simulate_match(player_1, opponent_, strategy, rounds)
  File "/home/travis/build/Axelrod-Python/Axelrod/axelrod/strategies/mindreader.py", line 11, in simulate_match
    play_1, play_2 = strategy, player_2.strategy(player_1)
  File "/home/travis/build/Axelrod-Python/Axelrod/axelrod/strategy_transformers.py", line 87, in strategy
    *args, **kwargs)
  File "/home/travis/build/Axelrod-Python/Axelrod/axelrod/strategy_transformers.py", line 191, in final_sequence
    return seq[-index]
IndexError: list index out of range

```

**Comment by drvinceknight** [comment]
Currently working on it.

**Comment by drvinceknight** [comment]
#466 fixes this but that's a temporary fix as hypothesis seems to have found some set of strategies for which a tournament will fail on py2:

Strategies for which this fails:

- <class 'axelrod.strategies.memoryone.ALLCorALLD'>,
- <class 'axelrod.strategies.grudger.Aggravater'>,
- <class 'axelrod.strategy_transformers.BackStabber'>,
- <class 'axelrod.strategies.alternator.Alternator'>,
- <class 'axelrod.strategies.mindreader.MindReader'>]

Here are the other parameters (all that is spat out by Hypothesis):

- turns=2,
- repetitions=2,
- random.seed: 0

As I mentioned on gitter, I don't think any bug was actually introduced but simply that hypothesis has found something.

**Comment by drvinceknight** [comment]
Smallest reproduction of this (this is not a py2 or py3 thing apparently):

```
>>> p1 = axl.BackStabber()
>>> p2 = axl.MindReader()
>>> s = [p1, p2]
>>> t = axl.Tournament(s, turns=2)
>>> t.play()
...
/Users/vince/src/Axelrod/axelrod/strategy_transformers.py in final_sequence(player, opponent, action, seq)
    189     index = length - len(player.history)
    190     if index <= len(seq):
--> 191         return seq[-index]
    192     return action
    193

IndexError: list index out of range
```

With more than 2 rounds gives the same results. 

Also it seems to be this particular setup of `MinderReader` vs `BackStabber`. `Cooperator` v `BackStabber` works without a problem as does `MindReader` v `Cooperator`.

**Comment by marcharper** [comment]
Could it be a hypothesis version issue? I don't get this when running the tests locally.

**Comment by drvinceknight** [comment]
Have answered on gitter (thinking it might be quicker if we're both around). Basically: no, BackStabber and MindReader can't play together. Investigating more.
