### ISSUE TITLE
Sphinx not building docs

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/Axelrod#822]
We have the following sphinx error:

```
Running Sphinx v1.3.5
making output directory...

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/axelrod/envs/master/lib/python3.4/site-packages/sphinx/cmdline.py", line 243, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/axelrod/envs/master/lib/python3.4/site-packages/sphinx/application.py", line 127, in __init__
    confoverrides or {}, self.tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/axelrod/envs/master/lib/python3.4/site-packages/sphinx/config.py", line 277, in __init__
    execfile_(filename, config)
  File "/home/docs/checkouts/readthedocs.org/user_builds/axelrod/envs/master/lib/python3.4/site-packages/sphinx/util/pycompat.py", line 128, in execfile_
    exec_(code, _globals)
  File "conf.py", line 32, in <module>
    import axelrod
  File "/home/docs/checkouts/readthedocs.org/user_builds/axelrod/checkouts/master/axelrod/__init__.py", line 9, in <module>
    from .actions import Actions, flip_action
  File "/home/docs/checkouts/readthedocs.org/user_builds/axelrod/checkouts/master/axelrod/actions.py", line 1, in <module>
    from typing import NewType
ImportError: No module named 'typing'

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/axelrod/checkouts/master/axelrod/actions.py", line 1, in <module>
    from typing import NewType
ImportError: No module named 'typing'
The full traceback has been saved in /tmp/sphinx-err-6uem1855.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!

```

Looks like it's due to the typing module which might not be in the version of python 3 I've configured to run in `.readthedocs.yml`.

Trying a fix now.

**Comment by drvinceknight** [comment]
https://github.com/rtfd/readthedocs.org/issues/1990

**Comment by drvinceknight** [comment]
On the `822` branch I've tried two separate fixes:

- Call for native py3.6 but that's not supported yet.
- Use a conda environment. This seems to work for the build but getting a syntax error on the `actions.py` file which has some type annotations:

```
Running Sphinx v1.3.5
making output directory...

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/axelrod/conda/822/lib/python2.7/site-packages/Sphinx-1.3.5-py2.7.egg/sphinx/cmdline.py", line 243, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/axelrod/conda/822/lib/python2.7/site-packages/Sphinx-1.3.5-py2.7.egg/sphinx/application.py", line 127, in __init__
    confoverrides or {}, self.tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/axelrod/conda/822/lib/python2.7/site-packages/Sphinx-1.3.5-py2.7.egg/sphinx/config.py", line 279, in __init__
    raise ConfigError(CONFIG_SYNTAX_ERROR % err)
ConfigError: There is a syntax error in your configuration file: invalid syntax (actions.py, line 10)

Configuration error:
There is a syntax error in your configuration file: invalid syntax (actions.py, line 10)
```

Any help appreciated.

**Comment by drvinceknight** [comment]
Here's the build on rtd: https://readthedocs.org/projects/axelrod/builds/4904820/
